[package]
name = "aks"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust implementation of AKS Primality Test"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
